"""empty message

Revision ID: 85a794525e48
Revises: 
Create Date: 2023-06-02 00:36:05.188713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a794525e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_dht', sa.Float(), nullable=True),
    sa.Column('humidity_dht', sa.Float(), nullable=True),
    sa.Column('temperature_ext', sa.Float(), nullable=True),
    sa.Column('temperature_int', sa.Float(), nullable=True),
    sa.Column('temperature_bmp', sa.Float(), nullable=True),
    sa.Column('airpreassure', sa.Float(), nullable=True),
    sa.Column('ligth_infrared', sa.Float(), nullable=True),
    sa.Column('ligth_lux', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_id'), 'temperature', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_id'), table_name='temperature')
    op.drop_table('temperature')
    # ### end Alembic commands ###
